### ISSUE TITLE
Input element without type

### ISSUE THREAD

**Issue by YankoSantos** [milligram/milligram.github.io#22]
There is a small patch to be made in version 1.2.3 of the milligran.
When creating an input element and not defining the type (Ex: <input name = "id" />) the library is not assigning a default style for the element.

### Steps to reproduce
Create a input and not defining the type 
http://codepen.io/yankosantos/pen/woxrZZ

### Expected behavior
It is expected to apply the style default (text) in element

### Actual behavior
No aplicate style

### System configuration
**Node version**:
v6.9.2

**npm version**:
3.10.7

**Comment by cjpatoilo** [comment]
Hi @YankoSantos. [Check this](https://github.com/milligram/milligram/blob/master/src/_Form.sass), in fact this was thought. To answer to this question we can refer to:

[HTML4 SPEC 17.4 The INPUT element](http://www.w3.org/TR/html401/interact/forms.html#h-17.4)

`type = text|password|checkbox|radio|submit|reset|file|hidden|image|button [CI] This attribute specifies the type of control to create. The default value for this attribute is "text".`

[The HTML5 Spec 4.10.5 The input element](http://www.w3.org/TR/html5/forms.html#the-input-element)

`The type attribute controls the data type (and associated control) of the element. It is an enumerated attribute. The missing value default is the Text state.`

So, omitting the attribute is not considerable a bad practice but I can keep the framework lighter and fast. In the future I will extend support for all elements of the new specification. 

Thanks for attention <3
