### ISSUE TITLE
Replace RawGit with alternative CDN

### ISSUE THREAD

**Issue by garas** [milligram/milligram.github.io#29]
Website currently suggest RawGit as CDN. But _RawGit is now in a sunset phase and will soon shut down_ ([rawgit.com](https://rawgit.com/)).

Replace it with some other CDN so user who will use `<link>` with this CDN will not get broken website some day.

I suggest https://cdnjs.com/libraries/milligram as alternative.

**Comment by cjpatoilo** [comment]
@garas thanks for the reporting. I will make the changes to @cdnjs 💪
